name: RoR

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: change directory
        run: cd hoge
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Setup database
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
      - name: Run tests
        run: |
          rails test
